parameters:
    database_driver: pdo_mysql
    database_host: localhost
    database_port: null
    database_name: tdd_mvc_app
    database_user: root
    database_password: qazwsxedc
    mailer_transport: smtp
    mailer_host: localhost
    mailer_user: null
    mailer_password: null
    locale: en
    secret: 8f0e06936b91d570b5f918d11b0b1b036c9abdbb
    database_path: null
